{% set name = "napari-czann-segment" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-czann-segment-{{ version }}.tar.gz
  sha256: 0c35fef64e07aa5a6e5c74603f40cb55b00d0e72492e777378ee0b6e2f9e68c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - aicsimageio
    - czmodel
    - cztile
    - magicgui
    - napari
    - numpy
    - onnxruntime
    - python >=3.8
    - qtpy
    - dask-core
    - scikit-image
    - tqdm

test:
  imports:
    - napari_czann_segment
  commands:
    - pip list
    # - pip check  # tf2onnx 1.8.5 has requirement flatbuffers~=1.12
  requires:
    - pip

about:
  home: https://github.com/sebi06/napari-czann-segment
  summary: Segmention using DeepLearning ONNX models packaged as *.czann files
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - sebi06
