{% set name = "napari-czann-segment" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-czann-segment-{{ version }}.tar.gz
  sha256: aa8bf22f02c914dfbf43fa59785e8fdb77cb55d9a18639ef13b3275ab1e628da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - aicsimageio
    - czmodel >=5
    - cztile
    - dask-core
    - magicgui
    - napari
    - numpy
    - onnxruntime
    - python >=3.8
    - pytorch
    - qtpy
    - scikit-image
    - tifffile >=2023.4.12
    - tqdm

test:
  imports:
    - napari_czann_segment
  commands:
    - pip list
    # - pip check 
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-czann-segment
  summary: Segmention using DeepLearning ONNX models packaged as *.czann files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/sebi06/napari-czann-segment

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - sebi06
